 #coding:utf-8
#--author-- lanhua.zhou

__all__ = ["Constants"]

class Constants(object):
    _scale = 2
    THUMBNAIL_SIZE = [144,81]
    ITEM_DELEGATE_SIZE = [200,81]
    BACKGROUND_COLOR = "#F0F0F0"
    INFO_BACKGROUND_COLOR = "#F0F0F0"
    INFO_TEXT_COLOR = "#000000"


# coding:utf-8
# --author-- lanhua.zhou

from Qt import QtCore

SELECT_BACKGROUND_COLOR = "#D9D9D9"
HOVER_BACKGROUND_COLOR = "#D3D3D3"
BACKGROUND_COLOR = "#FFFFFF"

# 空隙
INTERSTICE = 1

DELEGATE_HEIGHT = 36
TYPE_DELEGATE_HEIGHT = 36
ASSET_DELEGATE_HEIGHT = 36
TASK_DELEGATE_HEIGHT = 36
SHOT_DELEGATE_HEIGHT = 36
SEQUENCE_DELEGATE_HEIGHT = 36
EPISODE_DELEGATE_HEIGHT = 36

HEADER_HEIGHT = 50

ICON_WIDHT = 20
ICON_HEIGHT = 20

USER_THUMBNAIL_INTERSTICE = 2

class MousePoint:
    pos = QtCore.QPoint(0,0)


INFO_BACKGROUND_COLOR = "#FFFFFF"
INFO_TEXT_COLOR = "#000000"

_scale = 0.8

THUMBNAIL_SIZE = [192*_scale, 108*_scale*0]
ITEM_DELEGATE_SIZE = [192*_scale, 108*_scale*0 + 100]
BACKGROUND_COLOR = "#F0F0F0"

PLAY_ICON_SIZE = [60, 60]