# coding:utf-8
# --author-- lanhua.zhou

from Qt import QtCore

SELECT_BACKGROUND_COLOR = "#D9D9D9"
HOVER_BACKGROUND_COLOR = "#D3D3D3"
BACKGROUND_COLOR = "#FFFFFF"

# 空隙
INTERSTICE = 1

DELEGATE_HEIGHT = 60
TYPE_DELEGATE_HEIGHT = 36
ASSET_DELEGATE_HEIGHT = 36
TASK_DELEGATE_HEIGHT = 36
SHOT_DELEGATE_HEIGHT = 36
SEQUENCE_DELEGATE_HEIGHT = 36
EPISODE_DELEGATE_HEIGHT = 36

HEADER_HEIGHT = 50

ICON_WIDHT = 20
ICON_HEIGHT = 20

USER_THUMBNAIL_INTERSTICE = 2

class MousePoint:
    pos = QtCore.QPoint(0,0)