 #coding:utf-8
#--author-- lanhua.zhou

__all__ = ["Constants", "THUMBNAIL_SIZE"]

THUMBNAIL_SIZE = [225, 90]
ITEM_DELEGATE_SIZE = [225,200]
BACKGROUND_COLOR = "#F0F0F0"
PROJECT_BACKGROUND_COLOR = "#FFFFFF"
PROJECT_NAME_COLOR = "#5C5C5C"
STATUS_BACKGROUND_COLOR = "#E6E9ED"
STATUS_NAME_COLOR = "#FFFFFF"
THUMBNAIL_HEIGHT = 90
COLOR_DIAMETER = ITEM_DELEGATE_SIZE[0]/8

class Constants(object):
    THUMBNAIL_SIZE = [225, 90]
    ITEM_DELEGATE_SIZE = [225,200]
    BACKGROUND_COLOR = "#F0F0F0"
    PROJECT_BACKGROUND_COLOR = "#FFFFFF"
    PROJECT_NAME_COLOR = "#5C5C5C"
    STATUS_BACKGROUND_COLOR = "#E6E9ED"
    STATUS_NAME_COLOR = "#FFFFFF"
    THUMBNAIL_HEIGHT = 90